Repository codeconnector/CodingDojo, pull requests merged in 2021-10, with the labels that each got.

#192 update : add reference to issue number
  .github/ISSUE_TEMPLATE/hacktoberfest-template.md
Labels: hacktoberfest

#196 Challenge setup for 10-05-2021 Limited Levenshtein Leap
  challenges/2021-10-05-limited-levenshtein-leap/.gitignore
  challenges/2021-10-05-limited-levenshtein-leap/challenge.md
  challenges/2021-10-05-limited-levenshtein-leap/package.json
  challenges/2021-10-05-limited-levenshtein-leap/run-tests
  challenges/2021-10-05-limited-levenshtein-leap/solution.js
  challenges/2021-10-05-limited-levenshtein-leap/solution.test.js
  challenges/2021-10-05-limited-levenshtein-leap/solutions/mob/.placeholder
Labels: challenge setup

#195 Java solution to SingleAndReadyToMingle
  challenges/2021-04-13-single-and-ready-to-mingle/solutions/java/jesse-moore/SingleAndReadyToMingle.java
Labels: hacktoberfest, hacktoberfest-accepted

#193 [Hacktoberfest] Python | Non-Constructible Change
  .gitignore
  challenges/2021-05-11-nonconstructible-change/.gitignore
  challenges/2021-05-11-nonconstructible-change/solutions/python/non_constructible_change.py
  challenges/2021-05-11-nonconstructible-change/solutions/python/non_constructible_change_test.py
Labels: hacktoberfest, hacktoberfest-accepted

#190 Add Bash solution for Balanced Brackets, with tests
  challenges/2021-07-20-balanced-brackets/solutions/bash/ericwburden/ericwburden.sh
  challenges/2021-07-20-balanced-brackets/solutions/bash/ericwburden/ericwburden_test.sh
Labels: hacktoberfest, hacktoberfest-accepted

#201 Add solution for limited levenshtein leap
  challenges/2021-10-05-limited-levenshtein-leap/solutions/mob/mob.js
Labels: hacktoberfest, hacktoberfest-accepted
