Repository codeconnector/CodingDojo, pull requests merged in 2022-10, with the labels that each got.

#344 solved 'skip-counting' puzzle | Javascript. ( issue #343 )
  challenges/2022-04-12-skip-counting/solutions/javascript/saimaheshtaduri/solution.js
Labels: hacktoberfest-accepted

#347 Added Simple 2D Iterator Solution in java
  challenges/2021-06-08-simple-2d-iterator/solutions/java/codingis4noobs2/Codingis4noobs2.java
Labels: hacktoberfest-accepted

#350 Program for minimum Sum of Squares in Java
  challenges/2021-05-18-sum-of-squares/solutions/java/divyansh-ag-03/divyanshAg03.java
Labels: hacktoberfest-accepted

#354 fix Variable name in JS tests (breaking bug)
  challenges/2022-10-11-blast-from-the-past/setups/javascript/solution.test.js
Labels: bug

#352 Ruby setup
  challenges/2022-10-11-blast-from-the-past/setups/ruby/info.md
  challenges/2022-10-11-blast-from-the-past/setups/ruby/solution.rb
Labels: challenge setup

#355 Blast from the Past csharp setup
  challenges/2022-10-11-blast-from-the-past/setups/csharp/BlastfromthePast.cs
  challenges/2022-10-11-blast-from-the-past/setups/csharp/BlastfromthePast.csproj
  challenges/2022-10-11-blast-from-the-past/setups/csharp/info.md
  challenges/2022-10-11-blast-from-the-past/setups/csharp/run-tests
Labels: challenge setup

#363 Eric's solution in Julia
  challenges/2022-10-11-blast-from-the-past/solutions/julia/ericwburden/ericwburden.jl
Labels: hacktoberfest-accepted

#362 JS solution for dojo 20221011
  challenges/2022-10-11-blast-from-the-past/setups/javascript/solution.test.js
  challenges/2022-10-11-blast-from-the-past/solutions/javascript/brehberg/brehberg.js
Labels: hacktoberfest-accepted

#366 Harrison's Javascript solution to blast-from-past
  challenges/2022-10-11-blast-from-the-past/solutions/javascript/Harrified/solution.js
Labels: hacktoberfest-accepted

#365 Blast from the past Moses Alero
  challenges/2022-06-14-two-sum-numbers/solutions/javascript/Moses-Alero/TwosumNumbers.js
  challenges/2022-10-11-blast-from-the-past/solutions/javascript/moses-alero/info.md
  challenges/2022-10-11-blast-from-the-past/solutions/javascript/moses-alero/package.json
  challenges/2022-10-11-blast-from-the-past/solutions/javascript/moses-alero/solution.js
  challenges/2022-10-11-blast-from-the-past/solutions/javascript/moses-alero/solution.test.js
Labels: hacktoberfest-accepted

#364 Justin's solution in JavaScript
  challenges/2022-10-11-blast-from-the-past/solutions/javascript/justinmemphis/justinmemphis.js
Labels: hacktoberfest-accepted

#361 multiple solutions in go, meeting the reqs :D
  challenges/2022-10-11-blast-from-the-past/solutions/go/drkennetz/go.mod
  challenges/2022-10-11-blast-from-the-past/solutions/go/drkennetz/go.sum
  challenges/2022-10-11-blast-from-the-past/solutions/go/drkennetz/solution.go
  challenges/2022-10-11-blast-from-the-past/solutions/go/drkennetz/solution_test.go
Labels: hacktoberfest-accepted

#368 Justin's solution in JavaScript plus test setup
  challenges/2022-09-12-find-those-fives/setups/javascript/info.md
  challenges/2022-09-12-find-those-fives/setups/javascript/package.json
  challenges/2022-09-12-find-those-fives/setups/javascript/solution.js
  challenges/2022-09-12-find-those-fives/setups/javascript/solution.test.js
  challenges/2022-09-12-find-those-fives/solutions/javascript/justinmemphis.js
Labels: hacktoberfest-accepted

#369 Added python solutions for Two Sum Numbers
  challenges/2022-06-14-two-sum-numbers/solutions/python/xcelr8/xcelr8.py
Labels: hacktoberfest-accepted

#372 R solution to Data Grouping challenge
  challenges/2021-11-16-data-grouping/solutions/R/ericwburden/ericwburden.R
Labels: hacktoberfest-accepted

#377 finished simple db in go
  challenges/2022-02-09-simple-db/solutions/go/drkennetz/drkennetz.go
  challenges/2022-02-09-simple-db/solutions/go/drkennetz/drkennetz_test.go
  challenges/2022-02-09-simple-db/solutions/go/drkennetz/go.mod
  challenges/2022-02-09-simple-db/solutions/go/drkennetz/go.sum
Labels: hacktoberfest-accepted

#371 Justin python solution blast from the past
  challenges/2022-10-11-blast-from-the-past/solutions/python/justinmemphis/justinmemphis.py
Labels: hacktoberfest-accepted
